server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: GAME-APP
  jmx:
    default-domain: GAME-APP

  datasource:
    url: jdbc:mysql://localhost:3306/game?characterEncoding=utf8&serverTimezone=GMT%2B8
    #url: jdbc:mysql://192.168.0.1:3306/test?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #以下为连接池的相关参数配置
    dbcp2:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

    tomcat:
      max-wait: 10000

  jpa:
    database: MYSQL
    show-sql: true
    ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect


debug: true
#日志等级
#logging:
#  level: debug




#图片下载地址
#custom:
#    tmpLocation: D:/ImageDownload







